function createconfusionmatrix(MATRIX, CLim, MIN,MAX,UVT)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 20-Sep-2013 12:12:42

% Create figure


figure1 = figure('PaperSize',[20.98404194812 29.67743169791],...
     'Colormap',[0.0416666679084301 0 0;0.201388895511627 0 0;0.361111104488373 0 0;0.520833313465118 0 0;0.680555582046509 0 0;0.840277791023254 0 0;1 0 0;1 0.125 0;1 0.25 0;1 0.375 0;1 0.5 0;1 0.625 0;1 0.75 0;1 0.875 0;1 1 0;1 1 0.0232493001967669;1 1 0.0464986003935337;1 1 0.0697479024529457;1 1 0.0929972007870674;1 1 0.11624650657177;1 1 0.139495804905891;1 1 0.209243699908257;1 1 0.278991609811783;1 1 0.348739504814148;1 1 0.418487399816513;1 1 0.488235294818878;1 1 0.557983219623566;1 1 0.627731084823608;1 1 0.697479009628296;1 1 0.767226874828339;1 1 0.836974799633026;1 1 0.906722664833069;1 1 0.976470589637756;1 1 0.977229595184326;1 1 0.977988600730896;1 1 0.978747606277466;1 1 0.97950667142868;1 1 0.98026567697525;1 1 0.98102468252182;1 1 0.98178368806839;1 1 0.98254269361496;1 1 0.98330169916153;1 1 0.984060704708099;1 1 0.984819710254669;1 1 0.985578775405884;1 1 0.986337780952454;1 1 0.987096786499023;1 1 0.987855792045593;1 1 0.988614797592163;1 1 0.989373803138733;1 1 0.990132808685303;1 1 0.990891814231873;1 1 0.991650879383087;1 1 0.992409884929657;1 1 0.993168890476227;1 1 0.993927896022797;1 1 0.994686901569366;1 1 0.995445907115936;1 1 0.996204912662506;1 1 0.996963918209076;1 1 0.997722983360291;1 1 0.99848198890686;1 1 0.99924099445343;1 1 1]);


% Create axes
if nargin==5
    Ticks = (MAX-MIN)./2 + MIN ;
    axes1 = axes('Parent',figure1,'YTick', Ticks, 'YTickLabel',UVT,...
    'YDir','reverse',...
    'XTick', Ticks, 'XTickLabel',UVT,...
    'Layer','top',...
    'CLim',CLim, 'TickLength',[0 0]);
elseif nargin==2
    axes1 = axes('Parent',figure1,...
    'YDir','reverse',...
    'Layer','top',...
    'CLim',CLim, 'TickLength',[0 0]);
end

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 149.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 149.5]);
%box(axes1,'on');
hold(axes1,'all');

% Create image
image(MATRIX,'Parent',axes1,'CDataMapping','scaled');
if nargin==5
    axis([0.5 MAX(end)+0.5 0.5 MAX(end)+0.5])
elseif nargin==2
    axis([0.5 size(MATRIX,1)+0.5 0.5 size(MATRIX,1)+0.5])
end

% Create colorbar
colorbar('peer',axes1);

%add some legend
xlabel('Predicted Vocalization');
ylabel('Actual Vocalization');

